/**
 * Origin Certificate PFX Generator - Cloudflare Worker
 * 
 * A secure, client-side tool for converting Cloudflare Origin Certificates
 * to PKCS#12 (PFX) format for Windows servers.
 * 
 * This Worker serves the Astro-generated static site and provides
 * server-side utilities like logging and KV access for Root CAs.
 */

import type { KVNamespace, ExecutionContext } from '@cloudflare/workers-types';

// Environment interface - generated by `wrangler types`
export interface Env {
  ROOT_CA: KVNamespace;
  ENVIRONMENT: string;
}

/**
 * Security headers to add to all responses
 */
const securityHeaders = {
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'X-XSS-Protection': '1; mode=block',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload',
};

/**
 * Main request handler
 */
export default {
  async fetch(
    request: Request,
    env: Env,
    ctx: ExecutionContext
  ): Promise<Response> {
    try {
      // Handle the request
      const response = await handleRequest(request, env, ctx);
      
      // Add security headers to all responses
      const headers = new Headers(response.headers);
      Object.entries(securityHeaders).forEach(([key, value]) => {
        headers.set(key, value);
      });
      
      return new Response(response.body, {
        status: response.status,
        statusText: response.statusText,
        headers,
      });
    } catch (error) {
      // Log error for observability
      console.error('Worker error:', error);
      
      // Return structured error response
      return new Response(
        JSON.stringify({
          error: 'Internal Server Error',
          message: error instanceof Error ? error.message : 'Unknown error',
          timestamp: new Date().toISOString(),
        }),
        {
          status: 500,
          headers: {
            'Content-Type': 'application/json',
            ...securityHeaders,
          },
        }
      );
    }
  },
};

/**
 * Handle incoming requests
 */
async function handleRequest(
  request: Request,
  env: Env,
  ctx: ExecutionContext
): Promise<Response> {
  const url = new URL(request.url);
  
  // API endpoint for Root CA certificates
  if (url.pathname === '/api/root-ca' && request.method === 'GET') {
    return handleRootCARequest(request, env, ctx);
  }
  
  // Health check endpoint
  if (url.pathname === '/health') {
    return new Response(
      JSON.stringify({
        status: 'ok',
        timestamp: new Date().toISOString(),
        environment: env.ENVIRONMENT,
      }),
      {
        status: 200,
        headers: { 'Content-Type': 'application/json' },
      }
    );
  }
  
  // Serve static assets (Astro will handle this in production)
  // For local development, this will be handled by the dev server
  return fetch(request);
}

/**
 * Handle Root CA certificate requests
 */
async function handleRootCARequest(
  request: Request,
  env: Env,
  ctx: ExecutionContext
): Promise<Response> {
  const url = new URL(request.url);
  const type = url.searchParams.get('type');
  
  if (!type || !['rsa', 'ecc'].includes(type)) {
    return new Response(
      JSON.stringify({
        error: 'Invalid type parameter',
        message: 'Type must be "rsa" or "ecc"',
      }),
      {
        status: 400,
        headers: { 'Content-Type': 'application/json' },
      }
    );
  }
  
  try {
    // Fetch from KV - use waitUntil for non-blocking cache warming
    const cert = await env.ROOT_CA.get(type);
    
    if (!cert) {
      return new Response(
        JSON.stringify({
          error: 'Certificate not found',
          message: `Root CA certificate for type "${type}" not found in KV`,
        }),
        {
          status: 404,
          headers: { 'Content-Type': 'application/json' },
        }
      );
    }
    
    // Return certificate with proper content type
    return new Response(cert, {
      status: 200,
      headers: {
        'Content-Type': 'application/x-pem-file',
        'Cache-Control': 'public, max-age=86400', // Cache for 24 hours
      },
    });
  } catch (error) {
    console.error('KV fetch error:', error);
    throw error;
  }
}
